In [1]:
import numpy as np

In [2]:
np_array = np.array([1,2,3,4,5])
np_array

array([1, 2, 3, 4, 5])

In [3]:
np_array.shape

(5,)

In [4]:
x = np.zeros((3,4))
y = np.ones((3,4))
z = np.full((3,4), 2)
z

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [5]:
# Identity matrix
x = np.eye(5)
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [6]:
x = np.arange(0, 1, 0.1)
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [7]:
x = np.linspace(1, 50, 10).reshape((5,2))
x

array([[ 1.        ,  6.44444444],
       [11.88888889, 17.33333333],
       [22.77777778, 28.22222222],
       [33.66666667, 39.11111111],
       [44.55555556, 50.        ]])

In [8]:
x = np.random.random((3,3))
x

array([[0.48983623, 0.3256178 , 0.26099136],
       [0.38872204, 0.27533646, 0.7163225 ],
       [0.10865357, 0.98961149, 0.30046591]])

In [9]:
s = np.random.randint(5, 15, (3,3))
s

array([[10, 14, 13],
       [12,  7,  5],
       [ 8, 14, 11]])

In [10]:
x = np.random.normal(0, 0.1, (3, 3))
# Mean = 0, STDDEV = 0.1, shape = (3, 3)
x

array([[ 0.09305658,  0.15190342, -0.04183126],
       [-0.11926295,  0.10108474,  0.029773  ],
       [-0.04168308,  0.02786994, -0.09134196]])

In [11]:
np.delete(x, [0,1], axis = 0)    #Along the row   ---> Deletes 0th and 2th row

array([[-0.04168308,  0.02786994, -0.09134196]])

In [12]:
np.delete(x, [0], axis = 1)    #Along the column   ---> Deletes 0th column

array([[ 0.15190342, -0.04183126],
       [ 0.10108474,  0.029773  ],
       [ 0.02786994, -0.09134196]])

In [13]:
x = np.arange(0, 9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
x = np.append(x, [[1,2,3]], axis = 0)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [1, 2, 3]])

In [15]:
x = np.append(x, [[-1], [-1], [-1], [-4]], axis = 1)
x

array([[ 0,  1,  2, -1],
       [ 3,  4,  5, -1],
       [ 6,  7,  8, -1],
       [ 1,  2,  3, -4]])

In [16]:
# hstack and vstack functions for stacking on each other

# Slicing and Indicing

In [19]:
X = np.random.random((5,5))
X

array([[0.87856183, 0.28545749, 0.29534742, 0.56568719, 0.841155  ],
       [0.7043287 , 0.60784715, 0.02127375, 0.61190189, 0.01978487],
       [0.10965159, 0.69150448, 0.32850146, 0.45845198, 0.98388183],
       [0.6819189 , 0.10599687, 0.86394574, 0.05685541, 0.18367061],
       [0.15290865, 0.26561858, 0.54825812, 0.57257886, 0.80299108]])

In [20]:
X[2:, 2:]

array([[0.32850146, 0.45845198, 0.98388183],
       [0.86394574, 0.05685541, 0.18367061],
       [0.54825812, 0.57257886, 0.80299108]])

In [22]:
z = X.copy()
z

array([[0.87856183, 0.28545749, 0.29534742, 0.56568719, 0.841155  ],
       [0.7043287 , 0.60784715, 0.02127375, 0.61190189, 0.01978487],
       [0.10965159, 0.69150448, 0.32850146, 0.45845198, 0.98388183],
       [0.6819189 , 0.10599687, 0.86394574, 0.05685541, 0.18367061],
       [0.15290865, 0.26561858, 0.54825812, 0.57257886, 0.80299108]])

In [24]:
X.sort(axis=0)
X

array([[0.10965159, 0.10599687, 0.02127375, 0.05685541, 0.01978487],
       [0.15290865, 0.26561858, 0.29534742, 0.45845198, 0.18367061],
       [0.6819189 , 0.28545749, 0.32850146, 0.56568719, 0.80299108],
       [0.7043287 , 0.60784715, 0.54825812, 0.57257886, 0.841155  ],
       [0.87856183, 0.69150448, 0.86394574, 0.61190189, 0.98388183]])