# Introduction
NumPy is basic building blog for studying applied machine learning and deep learning through Python. It provides an efficient way for computing matrix calculations such as addition, subtraction, multiplication as well as computing transpose, inverse, eigen value and vectors etc.

## # Creating a vector
Use numpy.array to create one dimensional as well as multi-dimensional array.

In [2]:
import numpy as np
v1 = np.array([1, 2, 3])
v2 = np.array([[1],
              [2],
              [3]])
print('v1 = ', v1) 
print('v2 = \n', v2)

v1 =  [1 2 3]
v2 = 
 [[1]
 [2]
 [3]]


## # Creating sparse matrix
Given data with very few non-zero values, one can efficiently represent them using sparse matrix. A frequent situation in ML problem lies in huge data. However, most of the elements are zero. Consider an example where columns of matrix represent every Netflix movie, rows represent users and values of matrix show whether user has seen particular movie or not. In this case, intuitively we can say that most of the users won't watch more than 200-500 movies. There might be more than tens of thousands of movies and million rows. This results into most of the values will be zero.


Implementation of sparse matrix is out of scope of this tutorial. One can say we can use list of lists or dictionaries in this particular implementation. Enough theory, lets see an example.

In [9]:
from scipy import sparse

matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
[3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

matrix_sparse = sparse.csr_matrix(matrix_large)    #csr = Compressed Sparse Row
print(matrix_sparse)

  (1, 1)	1
  (2, 0)	3


Understand that (1, 1) 1 represents at index (1,1) non-zero value present is 1. Similarly at (2, 0) value present is 3.
No need to mention for coding wizards that index starts at 0. :p

## # Indexing and Slicing

In [12]:
# Create row vector
vector = np.array([1, 2, 3, 4, 5, 6])

# Select third element of vector
print(vector[2])

# Select second row, second column
print(matrix[1,1])

# Selects all elements
print(vector[:])

# Selecting upto 3rd index from start i.e., 0,1,2
print(vector[:3])

# Selecting everything after 3rd element to the end
print(vector[3:])

# Last element
print(vector[-1])

3
5
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]
6


In [16]:
# Create matrix
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

#Select first two rows and all columns
print(matrix[:2][:])

# Selects 1st and 2nd row along with all columns after 1
print('\n', matrix[1:3][1:])

[[1 2 3]
 [4 5 6]]

 [[7 8 9]]


## # Describing a matrix

In [3]:
# Create matrix
matrix = np.array([[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12]])

#View no of rows and columns
matrix.shape

(3, 4)

In [5]:
# View dimension of matrix
matrix.ndim

2

In [7]:
# Find min and max value
print(np.max(matrix))
print(np.min(matrix))

12
1


One important parameter of max or min function is 'axis'.
Here if we want to apply function along the columns (i.e. for each column, function will be applied) axis = 0 is provided. Thus for each column, we'll get a scalar value, which ultimately results into array of size equal to no. of columns.

In [9]:
np.max(matrix, axis= 0)

array([ 9, 10, 11, 12])

In [11]:
np.max(matrix, axis = 1)    # Here we'll get ans for each row, resulting into array of size equal to no. of rows

array([ 4,  8, 12])